spring:
  application:
    name: simulator
  threads:
    virtual:
      enabled: true

server:
  port: 80

sim:
  vendor: Bitmain
  model: Antminer S19j Pro
  firmware: 2025.11
  systemFilesystemVersion: 2025-11-01
  serialPrefix: SIM
  powerW: 3050
  hashrateThs: 104
  temperatureC: 67
  reboot-downtime: 30s
  poolUrl: stratum+tcp://pool.example.com:3333

  auth:
    username: root
    password: root

  cgminer:
    portsCsv: 4028,4029
    socketReadTimeoutMs: 1000
